### PR TITLE
Warn on illegal clones

### LINKED ISSUE #15: log's clone op can fail if you're storing a function on your state
the call to clone fails when you store a bound function on the state object.

deep clone is also a super expensive operation -- would love to figure out how we can do without a recursive deep-clone.

### PR DESCRIPTION
**Pull request by YerkoPalma**
should fix #15

Also add some docs on the `routes` property. If you think this should be on a different PR let me know, anyway I though it is a small docs tweak so it wouldn't matter to add it here.

devtools fix

### CODE REVIEW

File: lib/log.js [hunk 1]
```diff
@@ -51,7 +53,16 @@ function log (state, emitter, app, localEmitter) {
...
-      ? clone(state)
+      ? tryClone(state)
       : '<disabled>'
   }
+
+  function tryClone (state) {
+    try {
+      return clone(state)
+    } catch (ex) {
+      _log.warn('Could not clone your app state. Make sure to have a serializable state so it can be cloned')
```
Comment (yoshuawuyts) [inline lib/log.js]: This will create a huge amount of warnings; could we perhaps emit the warning once when people call `choo.log`? Perhaps we should set a flag that's toggled or something when we notice state cannot be serialized.

**Comment by YerkoPalma** [comment]
@yoshuawuyts I updated with the changes requested, should be enough I think :)

**Review by yoshuawuyts — APPROVED** [review]
LGTM

**Comment by yoshuawuyts** [comment]
`v2.2.0` :tada:
